-- Core schema for single-tenant CRM Lite in Supabase
-- Apply in Supabase SQL editor.

create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  email text not null unique,
  phone text,
  position text,
  role text not null default 'manager' check (role in ('admin', 'manager')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.clients (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text,
  phone text,
  company text,
  note text,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.deals (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  amount numeric(14, 2) not null default 0,
  stage text not null check (stage in ('lead', 'qualified', 'proposal', 'won', 'lost')),
  client_id uuid not null references public.clients(id) on delete cascade,
  comment text,
  owner_id uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.deal_stage_history (
  id bigint generated by default as identity primary key,
  deal_id uuid not null references public.deals(id) on delete cascade,
  from_stage text,
  to_stage text not null,
  changed_by uuid not null references public.profiles(id),
  changed_at timestamptz not null default now()
);

create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  entity_type text not null check (entity_type in ('client', 'deal', 'profile')),
  entity_id uuid not null,
  action text not null check (action in ('create', 'update', 'delete')),
  actor_id uuid not null references public.profiles(id),
  payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists clients_name_idx on public.clients(name);
create index if not exists clients_email_idx on public.clients(email);
create index if not exists clients_created_at_desc_idx on public.clients(created_at desc);
create index if not exists deals_stage_idx on public.deals(stage);
create index if not exists deals_client_id_idx on public.deals(client_id);
create index if not exists deals_owner_id_idx on public.deals(owner_id);
create index if not exists deals_updated_at_desc_idx on public.deals(updated_at desc);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_touch on public.profiles;
create trigger trg_profiles_touch
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists trg_clients_touch on public.clients;
create trigger trg_clients_touch
before update on public.clients
for each row execute function public.touch_updated_at();

drop trigger if exists trg_deals_touch on public.deals;
create trigger trg_deals_touch
before update on public.deals
for each row execute function public.touch_updated_at();

create or replace function public.current_role()
returns text
language sql
stable
as $$
  select p.role from public.profiles p where p.id = auth.uid();
$$;

create or replace function public.is_active_user()
returns boolean
language sql
stable
as $$
  select coalesce((select p.is_active from public.profiles p where p.id = auth.uid()), false);
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select public.current_role() = 'admin';
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email, role, is_active)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)),
    new.email,
    'manager',
    true
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.log_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_action text;
  v_entity_id uuid;
  v_payload jsonb;
begin
  if tg_op = 'INSERT' then
    v_action = 'create';
    v_entity_id = new.id;
    v_payload = to_jsonb(new);
  elsif tg_op = 'UPDATE' then
    v_action = 'update';
    v_entity_id = new.id;
    v_payload = jsonb_build_object('old', to_jsonb(old), 'new', to_jsonb(new));
  else
    v_action = 'delete';
    v_entity_id = old.id;
    v_payload = to_jsonb(old);
  end if;

  insert into public.activity_log(entity_type, entity_id, action, actor_id, payload)
  values (tg_argv[0], v_entity_id, v_action, auth.uid(), v_payload);
  return coalesce(new, old);
end;
$$;

create or replace function public.log_deal_stage_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.deal_stage_history (deal_id, from_stage, to_stage, changed_by)
    values (new.id, null, new.stage, auth.uid());
    return new;
  end if;

  if new.stage is distinct from old.stage then
    insert into public.deal_stage_history (deal_id, from_stage, to_stage, changed_by)
    values (new.id, old.stage, new.stage, auth.uid());
  end if;
  return new;
end;
$$;

drop trigger if exists trg_clients_activity on public.clients;
create trigger trg_clients_activity
after insert or update or delete on public.clients
for each row execute function public.log_activity('client');

drop trigger if exists trg_deals_activity on public.deals;
create trigger trg_deals_activity
after insert or update or delete on public.deals
for each row execute function public.log_activity('deal');

drop trigger if exists trg_profiles_activity on public.profiles;
create trigger trg_profiles_activity
after update on public.profiles
for each row execute function public.log_activity('profile');

drop trigger if exists trg_deals_stage_history on public.deals;
create trigger trg_deals_stage_history
after insert or update on public.deals
for each row execute function public.log_deal_stage_change();

alter table public.profiles enable row level security;
alter table public.clients enable row level security;
alter table public.deals enable row level security;
alter table public.deal_stage_history enable row level security;
alter table public.activity_log enable row level security;

drop policy if exists profiles_select_policy on public.profiles;
create policy profiles_select_policy on public.profiles
for select
to authenticated
using (
  public.is_active_user()
  and (public.is_admin() or id = auth.uid())
);

drop policy if exists profiles_update_self_policy on public.profiles;
create policy profiles_update_self_policy on public.profiles
for update
to authenticated
using (public.is_active_user() and id = auth.uid())
with check (
  id = auth.uid()
  and role = (select role from public.profiles where id = auth.uid())
  and is_active = (select is_active from public.profiles where id = auth.uid())
);

drop policy if exists profiles_update_admin_policy on public.profiles;
create policy profiles_update_admin_policy on public.profiles
for update
to authenticated
using (public.is_active_user() and public.is_admin())
with check (public.is_active_user() and public.is_admin());

drop policy if exists clients_select_policy on public.clients;
create policy clients_select_policy on public.clients
for select
to authenticated
using (public.is_active_user());

drop policy if exists clients_insert_policy on public.clients;
create policy clients_insert_policy on public.clients
for insert
to authenticated
with check (public.is_active_user() and created_by = auth.uid());

drop policy if exists clients_update_policy on public.clients;
create policy clients_update_policy on public.clients
for update
to authenticated
using (public.is_active_user())
with check (public.is_active_user());

drop policy if exists clients_delete_policy on public.clients;
create policy clients_delete_policy on public.clients
for delete
to authenticated
using (public.is_active_user() and public.is_admin());

drop policy if exists deals_select_policy on public.deals;
create policy deals_select_policy on public.deals
for select
to authenticated
using (public.is_active_user());

drop policy if exists deals_insert_policy on public.deals;
create policy deals_insert_policy on public.deals
for insert
to authenticated
with check (public.is_active_user() and owner_id = auth.uid());

drop policy if exists deals_update_policy on public.deals;
create policy deals_update_policy on public.deals
for update
to authenticated
using (public.is_active_user() and (public.is_admin() or owner_id = auth.uid()))
with check (public.is_active_user() and (public.is_admin() or owner_id = auth.uid()));

drop policy if exists deals_delete_policy on public.deals;
create policy deals_delete_policy on public.deals
for delete
to authenticated
using (public.is_active_user() and public.is_admin());

drop policy if exists stage_history_select_policy on public.deal_stage_history;
create policy stage_history_select_policy on public.deal_stage_history
for select
to authenticated
using (public.is_active_user());

drop policy if exists activity_log_select_policy on public.activity_log;
create policy activity_log_select_policy on public.activity_log
for select
to authenticated
using (public.is_active_user() and public.is_admin());
